### ISSUE TITLE
Support for XU4 and rebase against SM5

### ISSUE THREAD

**Issue by njfox** [meveric/stepmania-gles2#1]
Hi @meveric,

I'm considering an odroid XU4 for Stepmania and I came across your GLES port. Do you know if this fork is likely to work on the XU4? Also, do you have any ideas on how much work it would be to rebase against SM5? I'm not sure what version this codebase uses but it seems to be a couple of years old now.

**Comment by meveric** [comment]
The fork is a "general" GLESv2 port and should work on any board that has GLESv2 support.
I actually offer different images for ODROID boards and the game is available on all of these images via apt-get install.

I haven't tested new versions of SM in a while and lately there were a lot of changes that might come in handy.
It could be that newer versions now support GLESv2 out of the box, I think I've read something about it.
Even if it does not support GLESv2, we now can use gl4es (a OpenGL -> OpenGL ES wrapper) for OpenGL 2.0 content, which means shader work as well and this means, even a native OpenGL port might work "out of the box" on ODROIDs if run with gl4es drivers.

**Comment by njfox** [comment]
Great, thanks for the information--I've ordered the XU4 so I can ping you when I have a chance to start testing. Are you thinking I should just try building the latest SM release and go from there? Are there any dependencies you think I'll need for this board that aren't listed in the SM wiki (other than gl4es potentially)?

**Comment by meveric** [comment]
The dependencies for ODROIDs are the same as for Linux, there is no difference, the drivers and capabilities are different and that is what you have to deal with (OpenGL ES vs OpenGL, etc.) but the compiling etc. is the same  as for standard Linux.
If you want to compile it yourself make sure to check if there's a OpenGL ES option.

**Comment by njfox** [comment]
Based on shakesoda's [comment](https://github.com/stepmania/stepmania/issues/1418), there seem to be no real plans to optimize for OpenGL ES and it's pretty much unplayable on OpenGL ES directly. However, I've been running the latest Stepmania `master` with gl4es per your suggestion and it's been pretty much flawless. I didn't need to use any hacks or workarounds other than installing alsa-oss because Stepmania was having issues with my pulse driver for some reason.

I just wanted to say thanks @meveric and let you know the results in case you feel like updating your package in the odroid repositories to a newer version.

**Comment by meveric** [comment]
Thanks for the info!
I'll see if I can fit in a rebuild for ODROIDs and make a newer version available for ODROIDs :)
